### ISSUE TITLE
Request: USI Kontainers patch

### ISSUE THREAD

**Issue by RealKolago** [Angel-125/WildBlueTools#1]
I like your resource switching mod and the USI Kontainers mod but they can't switch storage in flight. 
Can you make a MM-Patch for USI Kontainers patching them to WBIConvertibleStorage with STORAGE_TEMPLATE using the USI textures?

https://github.com/BobPalmer/FTT/releases
https://github.com/BobPalmer/MKS/releases

**Comment by Angel-125** [comment]
I havent' used USI Kontainers in a long time, don't they already have resource switching? Anyway, you can easily create a Module Manager patch. Just copy the WBIConvertableStorage entry in, say, the Buckboard1000.cfg file and use that as a basis for a ModuleManager patch. You then need to set the capacityFactor to reflect the size of the container. WBT's templates are based upon a standard volume of 5600 liters (or 1800 units if using stock resources like Ore, MonoPropellant, LiquidFuel, and Oxidizer). If the USI Kontainer uses a stock resource, divide the total units by 1800 to determine the capacityFactor.

example

@PART[some-usi-part]:NEEDS[WildBlueTools]
{
    MODULE
    {
        name = ModuleKISInventory
        maxVolume = <multiply storage units of stock resource by 5>
        externalAccess = true
        internalAccess = true
        slotsX = 6
        slotsY = 6
        slotSize = 50
        itemIconResolution = 128
        selfIconResolution = 128
        openSndPath = KIS/Sounds/containerOpen
        closeSndPath = KIS/Sounds/containerClose
        defaultMoveSndPath = KIS/Sounds/itemMove
    }

```
MODULE
{
    name = WBIConvertibleStorage
    enableLogging = True

    //Determines if the module allows in-field reconfiguring
    fieldReconfigurable = True

    //Require a confirmation click before changing resources
    confirmResourceSwitch = True

    //Determines whether or not to show the context menu GUI
    showGUI = True

    //Short name of the default module template.
    //This is used when selecting the part in the editor.
    //User will then right-click on the module to change its type.
    defaultTemplate = LFO

    //name of the template nodes to use
    templateNodes = STORAGE_TEMPLATE

    //Some containers don't hold as much resources as the template specifies, while others hold more.
    //Since the resource templates specify base amounts, the capacity factor specifies a multiplier to
    //factor into the resource amounts.
```

 //Take the part's total resource unit capacity (use a stock resource container, one that holds Ore, for example) and divide by 1800 to get the capacityFactor
//If using a CommunityResourcePack resource like MetallicOre, divide the storage capacity of the tank by 5600.
        capacityFactor = 0.057

```
    //Name of the logo panel transforms. Assume USI Kontainers don't have decals
    decalsVisible = false

    //If the part has a KIS container, this is the base and max amount
    baseStorage = .001
    maxStorage = <multiply storage units of stock resource by 5>
}
```

}

**Comment by RealKolago** [comment]
Thanks, now I know how to do this for my game. But you can do it for everybody's USI Kontainers in your mod (as an optional MM Patch perhaps).

**Comment by Angel-125** [comment]
I could do that... I think RoverDude is going to completely revamp his stuff for KSP 1.2, so I'll wait until that happens, then revisit this. :) You could always create a patch and post what you did on the thread. :)
