### ISSUE TITLE
92 instances of decals using wrong path across WBI

### ISSUE THREAD

**Issue by Aelfhe1m** [Angel-125/WildBlueTools#15]
23 files in WBT, Buffalo, DSEV, Heisenberg, MOLE and Pathfinder have texture paths of `000WildBlueTools/CommonTemplates/Decals` despite the `CommonTemplates` folder no longer being present.

Below image contains full list (sorry couldn't find a way to get Notepad++ find in files result to save as text):

![](https://i.imgur.com/8qCLXgO.png)

**Comment by Angel-125** [comment]
Thanks, those must've slipped through when I was rearranging things.
