### ISSUE TITLE
Feature enhancement: Experiment classified whitelist

### ISSUE THREAD

**Issue by JadeOfMaar** [Angel-125/WildBlueTools#38]
An option for WBI powered experiments to have the celestial bodies whitelist be "classified" (with reference to your "<CLASSIFIED>" agent) when viewed in-game. Depending on the experiment this can be treated as spoiler and if left unclassified, would allow the player to instantly know which planet to bring the experiment to. The best case of this is an experiment that tells of clear potential for life or hidden, active life on a planet or moon that seems less attractive to visit.

Additionally, if possible and if you're inclined, the option to show a custom "failure" science result and give no science value when the experiment is run on a celestial body which is not on the whitelist.

**Comment by Angel-125** [comment]
WBIModuleScienceExperiment
 - Added showRequiredBodies field to hide the celestial bodies required to run an experiment. The default value is true.
 - Added requiredCelestialBodiesMsg to show a custom status message when the experiment isn't run on a required celestial body. The default value is "Failed to yield results."
