### ISSUE TITLE
Feature enhancement: Show altitude ranges in synopsis windows

### ISSUE THREAD

**Issue by JadeOfMaar** [Angel-125/WildBlueTools#39]
Currently, the altitude ranges of an experiment (when fixed) are only shown in the **Load Experiment** window. 
![imgur](https://i.imgur.com/l4AxFgP.png)

But not in **Module Info** or the part preview in part selection. The experiment **DSW Goo Evolution Study** is one that has fixed (undersea) altitude ranges.
![imgur](https://i.imgur.com/lDWTivB.png)

**Comment by Angel-125** [comment]
WBIModuleScienceExperiment
The default value is "Failed to yield results."
 - Fixed issue were minAltitude and maxAltitude weren't showing up.
