### ISSUE TITLE
WBIResearchContract log spam

### ISSUE THREAD

**Issue by KSAMissionCtrl** [Angel-125/WildBlueTools#9]
Put together a bare-minimum install and still seeing these messages in the log in the space center:

    targetBody could not be computed, using homeworld
    WBIResearchContract] - Trying to generate a contract, available count: 4/4

And in the flight scene it's just a non-stop spam of these messages. Save file is a career mode game.

[output_log.txt](https://github.com/Angel-125/WildBlueTools/files/875700/output_log.txt)

**Comment by KSAMissionCtrl** [comment]
I currently have WBI stuff removed because of this. Is more information needed?

**Comment by Angel-125** [comment]
Nope, that was removed last update.
